#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/eeprom.h>
#include <avr/pgmspace.h>
#include <util/delay.h>
#include "../lib/spi.h"
#include "../lib/m25p16.h"

#define BIT_SET(x,y) x |= _BV(y)
#define BIT_CLEAR(x,y) x &= ~(_BV(y))
#define BIT_TOGGLE(x,y) x ^= _BV(y)
#define BIT_WAVE(x,y) BIT_SET(x,y); _delay_ms(150); BIT_CLEAR(x,y); _delay_ms(150);

#define LED_PORT PORTB
#define LED_DDR DDRB
#define LED_PIN PB0

void static inline led_init()
{
	LED_DDR |= (1 << LED_PIN);
}

void static inline led_on()
{
	BIT_SET(LED_PORT, LED_PIN);
}

void static inline led_off()
{
	BIT_CLEAR(LED_PORT, LED_PIN);
}


#define MEM_START 0x0000
#define PART 0

void main(void)
{
	led_init();
	led_on();
	
	
	// insert output generated by "generate" here
	
	
	led_off();
	
	while (1)
	{
	}
}
